-- System Privileges
CREATE USER CELEBI IDENTIFIED BY CELEBI;
GRANT CONNECT, RESOURCE TO CELEBI;
GRANT CREATE ROLE TO MEHMET;


CREATE USER BILGE IDENTIFIED BY BILGE;
GRANT CONNECT, RESOURCE TO BILGE;
