CREATE USER CELEBI IDENTIFIED BY CELEBI;

SELECT TABLE_NAME FROM TABS;

-- Object Privileges
GRANT SELECT ON REGIONS TO CELEBI;

GRANT INSERT ON REGIONS TO CELEBI;

-- Yetkileri sadece kendisi kullanabilir. Celebi
GRANT UPDATE,DELETE ON REGIONS TO CELEBI;

-- Yetkiler baþkasýna da tranrsfer edebilir. Celebi
GRANT UPDATE,DELETE ON REGIONS TO CELEBI WITH GRANT OPTION;

-- TO CHECK PRIVS GIVEN
SELECT * FROM USER_TAB_PRIVS_MADE;

REVOKE SELECT ON REGIONS FROM CELEBI;

REVOKE DELETE,UPDATE ON REGIONS FROM CELEBI;

REVOKE INSERT ON REGIONS FROM CELEBI;

GRANT SELECT ON REGIONS TO PUBLIC;

-- ROLE
CREATE ROLE R_SELUPT;

CREATE ROLE R_INSDEL;

GRANT SELECT, UPDATE ON REGIONS TO R_SELUPT;

GRANT INSERT,DELETE ON REGIONS TO R_INSDEL;

GRANT R_SELUPT TO BILGE;

GRANT R_INSDEL TO CELEBI;

REVOKE UPDATE ON REGIONS FROM R_SELUPT;

REVOKE R_INSDEL FROM CELEBI;

DROP ROLE R_INSDEL;




