-- CURRENT_DATE, SYSDATE, SYSTIMESTAMP

SELECT CURRENT_DATE, SYSDATE FROM DUAL;

SELECT SESSIONTIMEZONE FROM DUAL;

ALTER SESSION SET TIME_ZONE = '+3:0';

SELECT SYSTIMESTAMP FROM DUAL;

SELECT  SYSDATE,
        TO_CHAR(SYSDATE, 'D') DAYOFWEEK,
        TO_CHAR(SYSDATE, 'DD') DAYOFMONTH,
        TO_CHAR(SYSDATE, 'DDD') DAYOFYEAR,
        TO_CHAR(SYSDATE, 'DAY') NAMEOFDAY,
        TO_CHAR(SYSDATE, 'Dy') NAMOFDAY,
        TO_CHAR(SYSDATE, 'W') WEEKOFMONTH,
        TO_CHAR(SYSDATE, 'WW') WEEKOFYEAR,
        TO_CHAR(SYSDATE, 'mm') MMOFYEAR,
        TO_CHAR(SYSDATE, 'MON') MMOFYEAR,
        TO_CHAR(SYSDATE, 'MONTH') MMOFYEAR,
        TO_CHAR(SYSDATE, 'YYYY') YEARR,
        TO_CHAR(SYSDATE, 'YEAR') YEARR,
        TO_CHAR(SYSDATE, 'HH24:MI:SS') TIMES,
        TO_CHAR(SYSDATE, 'DD/MM/YYYY HH24:MI:SS') TIMES
FROM DUAL;

